Use 2 virtual CPUs for Windows
pySmartDL gets threading errors with 1 CPU. Setting to 2 seems to fix.

Traceback (most recent call last):
  File "C:\d2iq\dcos\winpanda\common\storage.py", line 363, in add_package
    cm_utl.download(pkg_url, str(self.tmp_dpath))
  File "C:\d2iq\dcos\winpanda\common\utils.py", line 43, in download
    dl.start()
  File "C:\d2iq\dcos\winpanda\lib\python36\site-packages\pySmartDL\pySmartDL.py", line 318, in start
    self.wait(raise_exceptions=True)
  File "C:\d2iq\dcos\winpanda\lib\python36\site-packages\pySmartDL\pySmartDL.py", line 473, in wait
    self.post_threadpool_thread.join()
  File "C:\Python36\lib\threading.py", line 1051, in join
    raise RuntimeError("cannot join thread before it is started")
RuntimeError: cannot join thread before it is started

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\d2iq\dcos\winpanda\core\command.py", line 132, in execute
    dstor_pkgrepo_path=dstor_pkgrepo_path
  File "C:\d2iq\dcos\winpanda\common\storage.py", line 368, in add_package
    ) from e
core.exceptions.RCDownloadError: Add package: mesos--ff793b493b41b6226bccf5aaf217a80e64ac6039: http://172.28.128.20:80/windows/packages/mesos/mesos--ff793b493b41b6226bccf5aaf217a80e64ac6039.tar.xz: RuntimeError: cannot join thread before it is started